// What MSP alumni studied at their master's university, as percentages (no counts, no names).
// Generated by Alumni Office/DATABASE/_build_programmes.py from the local alumni database. Do not edit by hand.
// Universities with at least 10 alumni who named a programme; groups under 3 people merged into Other.
const UNIVERSITY_PROGRAMMES = {
 "Maastricht University": {
  "fields": [
   [
    "Biomedical & health sciences",
    33
   ],
   [
    "Neuroscience & psychology",
    19
   ],
   [
    "Data science & AI",
    11
   ],
   [
    "Medicine",
    9
   ],
   [
    "Engineering & materials",
    8
   ],
   [
    "Life sciences & biology",
    8
   ],
   [
    "Business, policy & society",
    5
   ],
   [
    "Sustainability & environment",
    4
   ],
   [
    "Chemistry",
    2
   ],
   [
    "Other",
    1
   ]
  ],
  "top": [
   [
    "Biomedical Sciences",
    24
   ],
   [
    "Biobased Materials",
    5
   ],
   [
    "Human Movement Science",
    4
   ],
   [
    "Systems Biology",
    4
   ]
  ]
 },
 "Utrecht University": {
  "fields": [
   [
    "Business, policy & society",
    24
   ],
   [
    "Biomedical & health sciences",
    20
   ],
   [
    "Life sciences & biology",
    18
   ],
   [
    "Sustainability & environment",
    12
   ],
   [
    "Physics & astronomy",
    7
   ],
   [
    "Medicine",
    6
   ],
   [
    "Engineering & materials",
    5
   ],
   [
    "Education & communication",
    4
   ],
   [
    "Data science & AI",
    3
   ],
   [
    "Other",
    2
   ]
  ],
  "top": [
   [
    "Science and Business Management",
    20
   ],
   [
    "Molecular and Cellular Life Sciences",
    12
   ],
   [
    "Drug Innovation",
    6
   ],
   [
    "Regenerative Medicine and Technology",
    5
   ]
  ]
 },
 "University of Amsterdam": {
  "fields": [
   [
    "Physics & astronomy",
    33
   ],
   [
    "Chemistry",
    25
   ],
   [
    "Biomedical & health sciences",
    18
   ],
   [
    "Data science & AI",
    10
   ],
   [
    "Neuroscience & psychology",
    4
   ],
   [
    "Other",
    10
   ]
  ],
  "top": [
   [
    "Physics and Astronomy",
    19
   ],
   [
    "Chemistry",
    18
   ],
   [
    "Biomedical Sciences",
    15
   ],
   [
    "Theoretical Physics",
    7
   ]
  ]
 },
 "Leiden University": {
  "fields": [
   [
    "Biomedical & health sciences",
    35
   ],
   [
    "Life sciences & biology",
    31
   ],
   [
    "Chemistry",
    10
   ],
   [
    "Physics & astronomy",
    8
   ],
   [
    "Data science & AI",
    6
   ],
   [
    "Other",
    10
   ]
  ],
  "top": [
   [
    "Biomedical Sciences",
    18
   ],
   [
    "Biology",
    8
   ],
   [
    "Molecular Genetics and Biotechnology",
    8
   ],
   [
    "Bio-Pharmaceutical Sciences",
    8
   ]
  ]
 },
 "Wageningen University & Research": {
  "fields": [
   [
    "Life sciences & biology",
    45
   ],
   [
    "Sustainability & environment",
    36
   ],
   [
    "Engineering & materials",
    7
   ],
   [
    "Other",
    11
   ]
  ],
  "top": [
   [
    "Forest and Nature Conservation",
    14
   ],
   [
    "Animal Sciences",
    11
   ],
   [
    "Biotechnology",
    9
   ],
   [
    "Plant Science",
    7
   ]
  ]
 },
 "Radboud University": {
  "fields": [
   [
    "Neuroscience & psychology",
    29
   ],
   [
    "Chemistry",
    24
   ],
   [
    "Life sciences & biology",
    15
   ],
   [
    "Physics & astronomy",
    12
   ],
   [
    "Biomedical & health sciences",
    10
   ],
   [
    "Sustainability & environment",
    7
   ],
   [
    "Other",
    2
   ]
  ],
  "top": [
   [
    "Molecular Chemistry",
    10
   ],
   [
    "Medicinal Chemistry",
    10
   ],
   [
    "Cognitive Neuroscience",
    7
   ]
  ]
 },
 "University of Groningen": {
  "fields": [
   [
    "Chemistry",
    32
   ],
   [
    "Sustainability & environment",
    24
   ],
   [
    "Medicine",
    20
   ],
   [
    "Biomedical & health sciences",
    12
   ],
   [
    "Other",
    12
   ]
  ],
  "top": [
   [
    "Chemistry",
    20
   ],
   [
    "Biomedical Sciences",
    12
   ],
   [
    "Marine Biology",
    12
   ],
   [
    "Molecular Medicine and Innovative Treatment",
    12
   ]
  ]
 },
 "KU Leuven": {
  "fields": [
   [
    "Biomedical & health sciences",
    23
   ],
   [
    "Engineering & materials",
    23
   ],
   [
    "Chemistry",
    18
   ],
   [
    "Other",
    36
   ]
  ],
  "top": [
   [
    "Biomedical Sciences",
    18
   ],
   [
    "Chemistry",
    14
   ]
  ]
 },
 "University of Copenhagen": {
  "fields": [
   [
    "Biomedical & health sciences",
    33
   ],
   [
    "Chemistry",
    19
   ],
   [
    "Life sciences & biology",
    19
   ],
   [
    "Other",
    29
   ]
  ],
  "top": [
   [
    "Human Biology",
    14
   ]
  ]
 },
 "Delft University of Technology": {
  "fields": [
   [
    "Engineering & materials",
    60
   ],
   [
    "Physics & astronomy",
    25
   ],
   [
    "Other",
    15
   ]
  ],
  "top": [
   [
    "Engineering and Policy Analysis",
    15
   ]
  ]
 },
 "Imperial College London": {
  "fields": [
   [
    "Biomedical & health sciences",
    21
   ],
   [
    "Medicine",
    16
   ],
   [
    "Chemistry",
    16
   ],
   [
    "Other",
    47
   ]
  ],
  "top": []
 },
 "Uppsala University": {
  "fields": [
   [
    "Sustainability & environment",
    29
   ],
   [
    "Chemistry",
    24
   ],
   [
    "Physics & astronomy",
    18
   ],
   [
    "Life sciences & biology",
    18
   ],
   [
    "Other",
    12
   ]
  ],
  "top": [
   [
    "Chemistry",
    18
   ]
  ]
 },
 "University College London": {
  "fields": [
   [
    "Life sciences & biology",
    31
   ],
   [
    "Neuroscience & psychology",
    19
   ],
   [
    "Other",
    50
   ]
  ],
  "top": []
 },
 "Vrije Universiteit Amsterdam": {
  "fields": [
   [
    "Biomedical & health sciences",
    40
   ],
   [
    "Data science & AI",
    20
   ],
   [
    "Other",
    40
   ]
  ],
  "top": []
 },
 "Lund University": {
  "fields": [
   [
    "Life sciences & biology",
    36
   ],
   [
    "Physics & astronomy",
    36
   ],
   [
    "Other",
    29
   ]
  ],
  "top": [
   [
    "Molecular Biology",
    21
   ]
  ]
 },
 "ETH Zurich": {
  "fields": [
   [
    "Engineering & materials",
    25
   ],
   [
    "Biomedical & health sciences",
    25
   ],
   [
    "Chemistry",
    25
   ],
   [
    "Other",
    25
   ]
  ],
  "top": []
 },
 "Karolinska Institutet": {
  "fields": [
   [
    "Biomedical & health sciences",
    73
   ],
   [
    "Other",
    27
   ]
  ],
  "top": []
 },
 "Eindhoven University of Technology": {
  "fields": [
   [
    "Chemistry",
    30
   ],
   [
    "Other",
    70
   ]
  ],
  "top": [
   [
    "Chemical Engineering",
    30
   ]
  ]
 }
};
